from google.cloud import bigquery

## CSV schemas
transform_dtypes = {
    'calendar_dtypes': {
        'Country': 'category',                    
        'Location': 'category',                    
        'Airbnb_ListingID': 'Int64',               
        'Calendar_Date': 'category',               
        'Calendar_Month': 'Int8',                  
        'Calendar_Year': 'Int16',                  
        'Stay_Week': 'category',                      
        'isAvailable': 'boolean',  
        'isBooked': 'boolean',                
        'Min_Nights': 'Int8',                      
        'Max_Nights': 'Int8',                      
        'Available_For_Checkin': 'Int8',        
        'Available_For_Checkout': 'Int8',
        'isAvailable_SequentialDays': 'Int16',
        'isUnavailable_SequentialDays': 'Int16',
        'RecordInserted': 'datetime64[ns]',
    },
    
    'description_dtypes': {
        'Country': 'category',
        'Location': 'category',
        'Airbnb_ListingID': 'Int64',
        'Scrape_Date': 'datetime64[ns]',
        'ReviewCount': 'Int32',
        'AccuracyRating': 'Float32',
        'CheckInRating': 'Float32',
        'CleanlinessRating': 'Float32',
        'CommunicationRating': 'Float32',
        'LocationRating': 'Float32',
        'ValueRating': 'Float32',
        'GuestSatisfactionOverall': 'Float32',
        'PictureCount': 'Int32',
        'CancellationPolicy': 'category',
        'LocationDescription': 'string',
        'LocationDescription_Localized': 'string',
        'ListingTitle': 'string',
        'ListingTitle_Localized': 'string',
        'MainDescription': 'string',
        'MainDescription_Localized': 'string',
        'SpaceDescription': 'string',
        'SpaceDescription_Localized': 'string',
        'GuestAccessDescription': 'string',
        'GuestAccessDescription_Localized': 'string',
        'RegistrationNumber': 'string',
        'CheckIn_Start': 'string',
        'CheckIn_End': 'string',
        'CheckOut_Start': 'string',
        'CheckOut_End': 'string',
        'HostAbout': 'string',
        'HostAbout_Localized': 'string',
        'HostName': 'string',
        'Host_RatingCount': 'Int32',
        'Host_RatingAverage': 'Float32',
        'Host_TimeMonths': 'Int16',
        'Host_TimeYears': 'Int16',
        'Host_isSuperhost': 'boolean',
        'Host_isVerified': 'boolean',
        'Host_BusinessType': 'category',
        'Host_ID': 'Int64',
        'Host_ResponseRate': 'string',
        'Host_ResponseTime': 'category',
        'Host_Highlights': 'string',
        'RoomTitles': 'string',
        'RoomSubTitles': 'string',
        'AdditionalHouseRules': 'string',
        'PhotoCaptions': 'string',
        'PhotoCaptions_Localized': 'string',
        'Amenities': 'string',
        'PaidPremiumCode': 'string',
        'RecordInserted': 'datetime64[ns]',
    }
}

bigquery_schemas = {
    'overviewSource': [
        bigquery.SchemaField("Country", "STRING"),
        bigquery.SchemaField("Location", "STRING"),
        bigquery.SchemaField("Airbnb_ListingID", "INT64"),
        bigquery.SchemaField("Scrape_Date", "DATE"),
        bigquery.SchemaField("Lat", "FLOAT64"),
        bigquery.SchemaField("Lng", "FLOAT64"),
        bigquery.SchemaField("City", "STRING"),
        bigquery.SchemaField("LocalizedCity", "STRING"),
        bigquery.SchemaField("LocalizedNeighborhood", "STRING"),
        bigquery.SchemaField("ListingTitle", "STRING"),
        bigquery.SchemaField("Bathrooms", "FLOAT64"),
        bigquery.SchemaField("Bedrooms", "FLOAT64"),
        bigquery.SchemaField("Beds", "FLOAT64"),
        bigquery.SchemaField("PersonCapacity", "INT64"),
        bigquery.SchemaField("is_NewListing", "BOOL"),
        bigquery.SchemaField("is_Superhost", "BOOL"),
        bigquery.SchemaField("PictureCount", "INT64"),
        bigquery.SchemaField("isLimitedAirbnbData", "BOOL"),
        bigquery.SchemaField("Host_Languages", "STRING"),
        bigquery.SchemaField("Host_ID", "INT64"),
        bigquery.SchemaField("Host_FirstName", "STRING"),
        bigquery.SchemaField("Host_isSuperhost", "BOOL"),
        bigquery.SchemaField("RoomType", "STRING"),
        bigquery.SchemaField("SpaceType", "STRING"),
        bigquery.SchemaField("RoomAndPropertyType", "STRING"),
        bigquery.SchemaField("ReviewCount", "INT64"),
        bigquery.SchemaField("AvgRating", "FLOAT64"),
        bigquery.SchemaField("StarRating", "FLOAT64"),
        bigquery.SchemaField("AmenityIDs", "STRING"),
        bigquery.SchemaField("BasicNightPrice_CheckIn", "DATE"),
        bigquery.SchemaField("BasicNightPrice_CheckOut", "DATE"),
        bigquery.SchemaField("Currency", "STRING"),
        bigquery.SchemaField("BasicNightPrice", "FLOAT64"),
        #bigquery.SchemaField("CleaningFee", "FLOAT64"),
        #bigquery.SchemaField("AirbnbServiceFee", "FLOAT64"),
        bigquery.SchemaField("Taxes", "FLOAT64"),
        bigquery.SchemaField("BasicNightPriceString_USD", "STRING"),
        bigquery.SchemaField("BasicNightPrice_USD", "FLOAT64"),
        #bigquery.SchemaField("CleaningFee_USD", "FLOAT64"),
        #bigquery.SchemaField("AirbnbServiceFee_USD", "FLOAT64"),
        bigquery.SchemaField("Taxes_USD", "FLOAT64"),
        bigquery.SchemaField("RecordInserted", "TIMESTAMP"),
    ],

    'calendarSource': [
        bigquery.SchemaField("Country", "STRING"),
        bigquery.SchemaField("Location", "STRING"),
        bigquery.SchemaField("Airbnb_ListingID", "INTEGER"),
        bigquery.SchemaField("Scrape_Date", "DATE"),
        bigquery.SchemaField("Calendar_Date", "DATE"),
        bigquery.SchemaField("DaysFrom_ScrapeDate", "INTEGER"),
        bigquery.SchemaField("Calendar_Month", "INTEGER"),
        bigquery.SchemaField("MonthsFrom_ScrapeDate", "INTEGER"),
        bigquery.SchemaField("Calendar_Year", "INTEGER"),
        bigquery.SchemaField("DayOfWeek", "STRING"),
        bigquery.SchemaField("DayOfWeek_Int", "INTEGER"),
        bigquery.SchemaField("Weekday_Or_Weekend", "STRING"),
        bigquery.SchemaField("isAvailable", "BOOLEAN"),
        bigquery.SchemaField("isBooked", "BOOLEAN"),
        bigquery.SchemaField("Min_Nights", "INTEGER"),
        bigquery.SchemaField("Max_Nights", "INTEGER"),
        bigquery.SchemaField("Available_For_Checkin", "BOOLEAN"),
        bigquery.SchemaField("Available_For_Checkout", "BOOLEAN"),
        bigquery.SchemaField("isAvailable_SequentialDays", "INTEGER"),
        bigquery.SchemaField("isUnavailable_SequentialDays", "INTEGER"),
        bigquery.SchemaField("PaidPremiumCode", "STRING"),
        bigquery.SchemaField("RecordInserted", "DATETIME")
    ],
    
    'pricingSource': [
        bigquery.SchemaField("Country", "STRING"),
        bigquery.SchemaField("Location", "STRING"),
        bigquery.SchemaField("Airbnb_ListingID", "INTEGER"),
        bigquery.SchemaField("Scrape_Date", "DATE"),
        bigquery.SchemaField("Guests", "INTEGER"),
        bigquery.SchemaField("Month", "INTEGER"),
        bigquery.SchemaField("Week_label", "STRING"),
        bigquery.SchemaField("Stay_Checkin", "DATE"),
        bigquery.SchemaField("Stay_Checkout", "DATE"),
        bigquery.SchemaField("Stay_Length_Actual", "INTEGER"),
        bigquery.SchemaField("Currency", "STRING"),
        bigquery.SchemaField("Price_Verbose", "STRING"),
        bigquery.SchemaField("Price_Per_Night", "FLOAT"),
        bigquery.SchemaField("Price_Per_Night_USD", "FLOAT"),
        bigquery.SchemaField("Discount_Description", "STRING"),
        bigquery.SchemaField("Discount_Amount", "FLOAT"),
        bigquery.SchemaField("Discount_Amount_USD", "FLOAT"),
        #bigquery.SchemaField("Cleaning_Fee", "FLOAT"),
        #bigquery.SchemaField("Cleaning_Fee_USD", "FLOAT"),
        #bigquery.SchemaField("Airbnb_Service_Fee", "FLOAT"),
        #bigquery.SchemaField("Airbnb_Service_Fee_USD", "FLOAT"),
        bigquery.SchemaField("Taxes", "FLOAT"),
        bigquery.SchemaField("Taxes_USD", "FLOAT"),
        bigquery.SchemaField("PaidPremiumCode", "STRING"),
        bigquery.SchemaField("RecordInserted", "DATETIME")
    ]

}


if __name__ == '__main__':
    from google.cloud import bigquery
    client = bigquery.Client()
    
    table_id = "doorbll-399214.sj_aircloud.src_airbnb_overview_new"
    
    # Create table object
    table = bigquery.Table(table_id, schema=bigquery_schemas['overviewSource'])
    
    # Create table in BigQuery
    table = client.create_table(table)  # API request